### ISSUE TITLE
prevent anyone from embedding the page in an iframe

### ISSUE THREAD

**Issue by aoberoi** [opentok/OpenTokRTC#72]
if we apply the header `X-Frame-Options: SAMEORIGIN` to the HTTP request, modern browsers will respect this by not embedding the page in an iframe.

**Comment by aullman** [comment]
Any specific reason why we don't want people to embed it in an iframe?

**Comment by aoberoi** [comment]
It sort of presents a loophole for people who want to use TokBox's services to host video meeting rooms inside their own sites/applications without being metered for usage.

**Comment by aullman** [comment]
Should we also prevent requests from other domains? I think right now we have an `Access-Control-Allow-Origin:*`.

**Comment by aoberoi** [comment]
@aullman that also seems reasonable. the only reason i could think of for *not* changing those CORS headers would be so that another client could be developed. i think internally, we've already found another solution for experimentation like that :wink:
